/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.demo.pojo.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class cityinUS extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5177588866055791353L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"cityinUS\",\"namespace\":\"io.confluent.demo.pojo.avro\",\"fields\":[{\"name\":\"city1\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"city2\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<cityinUS> ENCODER =
      new BinaryMessageEncoder<cityinUS>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<cityinUS> DECODER =
      new BinaryMessageDecoder<cityinUS>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<cityinUS> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<cityinUS> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<cityinUS> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<cityinUS>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this cityinUS to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a cityinUS from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a cityinUS instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static cityinUS fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String city1;
  @Deprecated public java.lang.String city2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public cityinUS() {}

  /**
   * All-args constructor.
   * @param city1 The new value for city1
   * @param city2 The new value for city2
   */
  public cityinUS(java.lang.String city1, java.lang.String city2) {
    this.city1 = city1;
    this.city2 = city2;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return city1;
    case 1: return city2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: city1 = (java.lang.String)value$; break;
    case 1: city2 = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'city1' field.
   * @return The value of the 'city1' field.
   */
  public java.lang.String getCity1() {
    return city1;
  }


  /**
   * Sets the value of the 'city1' field.
   * @param value the value to set.
   */
  public void setCity1(java.lang.String value) {
    this.city1 = value;
  }

  /**
   * Gets the value of the 'city2' field.
   * @return The value of the 'city2' field.
   */
  public java.lang.String getCity2() {
    return city2;
  }


  /**
   * Sets the value of the 'city2' field.
   * @param value the value to set.
   */
  public void setCity2(java.lang.String value) {
    this.city2 = value;
  }

  /**
   * Creates a new cityinUS RecordBuilder.
   * @return A new cityinUS RecordBuilder
   */
  public static io.confluent.demo.pojo.avro.cityinUS.Builder newBuilder() {
    return new io.confluent.demo.pojo.avro.cityinUS.Builder();
  }

  /**
   * Creates a new cityinUS RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new cityinUS RecordBuilder
   */
  public static io.confluent.demo.pojo.avro.cityinUS.Builder newBuilder(io.confluent.demo.pojo.avro.cityinUS.Builder other) {
    if (other == null) {
      return new io.confluent.demo.pojo.avro.cityinUS.Builder();
    } else {
      return new io.confluent.demo.pojo.avro.cityinUS.Builder(other);
    }
  }

  /**
   * Creates a new cityinUS RecordBuilder by copying an existing cityinUS instance.
   * @param other The existing instance to copy.
   * @return A new cityinUS RecordBuilder
   */
  public static io.confluent.demo.pojo.avro.cityinUS.Builder newBuilder(io.confluent.demo.pojo.avro.cityinUS other) {
    if (other == null) {
      return new io.confluent.demo.pojo.avro.cityinUS.Builder();
    } else {
      return new io.confluent.demo.pojo.avro.cityinUS.Builder(other);
    }
  }

  /**
   * RecordBuilder for cityinUS instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<cityinUS>
    implements org.apache.avro.data.RecordBuilder<cityinUS> {

    private java.lang.String city1;
    private java.lang.String city2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.demo.pojo.avro.cityinUS.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.city1)) {
        this.city1 = data().deepCopy(fields()[0].schema(), other.city1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.city2)) {
        this.city2 = data().deepCopy(fields()[1].schema(), other.city2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing cityinUS instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.demo.pojo.avro.cityinUS other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.city1)) {
        this.city1 = data().deepCopy(fields()[0].schema(), other.city1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city2)) {
        this.city2 = data().deepCopy(fields()[1].schema(), other.city2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'city1' field.
      * @return The value.
      */
    public java.lang.String getCity1() {
      return city1;
    }


    /**
      * Sets the value of the 'city1' field.
      * @param value The value of 'city1'.
      * @return This builder.
      */
    public io.confluent.demo.pojo.avro.cityinUS.Builder setCity1(java.lang.String value) {
      validate(fields()[0], value);
      this.city1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'city1' field has been set.
      * @return True if the 'city1' field has been set, false otherwise.
      */
    public boolean hasCity1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'city1' field.
      * @return This builder.
      */
    public io.confluent.demo.pojo.avro.cityinUS.Builder clearCity1() {
      city1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city2' field.
      * @return The value.
      */
    public java.lang.String getCity2() {
      return city2;
    }


    /**
      * Sets the value of the 'city2' field.
      * @param value The value of 'city2'.
      * @return This builder.
      */
    public io.confluent.demo.pojo.avro.cityinUS.Builder setCity2(java.lang.String value) {
      validate(fields()[1], value);
      this.city2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city2' field has been set.
      * @return True if the 'city2' field has been set, false otherwise.
      */
    public boolean hasCity2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city2' field.
      * @return This builder.
      */
    public io.confluent.demo.pojo.avro.cityinUS.Builder clearCity2() {
      city2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public cityinUS build() {
      try {
        cityinUS record = new cityinUS();
        record.city1 = fieldSetFlags()[0] ? this.city1 : (java.lang.String) defaultValue(fields()[0]);
        record.city2 = fieldSetFlags()[1] ? this.city2 : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<cityinUS>
    WRITER$ = (org.apache.avro.io.DatumWriter<cityinUS>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<cityinUS>
    READER$ = (org.apache.avro.io.DatumReader<cityinUS>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.city1);

    out.writeString(this.city2);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.city1 = in.readString();

      this.city2 = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.city1 = in.readString();
          break;

        case 1:
          this.city2 = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










