/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.demo.pojo.avro;
@org.apache.avro.specific.AvroGenerated
public enum ImmigrationStatus implements org.apache.avro.generic.GenericEnumSymbol<ImmigrationStatus> {
  E3, H1B, B1, B2  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ImmigrationStatus\",\"namespace\":\"io.confluent.demo.pojo.avro\",\"symbols\":[\"E3\",\"H1B\",\"B1\",\"B2\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
