// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caseV2.proto

package io.confluent.demo.pojo.protobuf;

public final class CaseV2Impl {
  private CaseV2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.confluent.demo.pojo.protobuf.Case)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 caseId = 1;</code>
     * @return The caseId.
     */
    long getCaseId();

    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string address = 4;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 4;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string email = 5;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 5;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
     * @return The enum numeric value on the wire for immigrationStatus.
     */
    int getImmigrationStatusValue();
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
     * @return The immigrationStatus.
     */
    io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus getImmigrationStatus();

    /**
     * <code>sint32 aNumber = 7;</code>
     * @return The aNumber.
     */
    int getANumber();
  }
  /**
   * Protobuf type {@code io.confluent.demo.pojo.protobuf.Case}
   */
  public  static final class Case extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.confluent.demo.pojo.protobuf.Case)
      CaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Case.newBuilder() to construct.
    private Case(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Case() {
      firstName_ = "";
      lastName_ = "";
      address_ = "";
      email_ = "";
      immigrationStatus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Case();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Case(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              caseId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              immigrationStatus_ = rawValue;
              break;
            }
            case 56: {

              aNumber_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.demo.pojo.protobuf.CaseV2Impl.internal_static_io_confluent_demo_pojo_protobuf_Case_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.demo.pojo.protobuf.CaseV2Impl.internal_static_io_confluent_demo_pojo_protobuf_Case_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.class, io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.Builder.class);
    }

    /**
     * Protobuf enum {@code io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus}
     */
    public enum ImmigrationStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>E3 = 0;</code>
       */
      E3(0),
      /**
       * <code>H1B = 1;</code>
       */
      H1B(1),
      /**
       * <code>B1 = 2;</code>
       */
      B1(2),
      /**
       * <code>B2 = 3;</code>
       */
      B2(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>E3 = 0;</code>
       */
      public static final int E3_VALUE = 0;
      /**
       * <code>H1B = 1;</code>
       */
      public static final int H1B_VALUE = 1;
      /**
       * <code>B1 = 2;</code>
       */
      public static final int B1_VALUE = 2;
      /**
       * <code>B2 = 3;</code>
       */
      public static final int B2_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ImmigrationStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ImmigrationStatus forNumber(int value) {
        switch (value) {
          case 0: return E3;
          case 1: return H1B;
          case 2: return B1;
          case 3: return B2;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ImmigrationStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ImmigrationStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ImmigrationStatus>() {
              public ImmigrationStatus findValueByNumber(int number) {
                return ImmigrationStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.getDescriptor().getEnumTypes().get(0);
      }

      private static final ImmigrationStatus[] VALUES = values();

      public static ImmigrationStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ImmigrationStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus)
    }

    public static final int CASEID_FIELD_NUMBER = 1;
    private long caseId_;
    /**
     * <code>int64 caseId = 1;</code>
     * @return The caseId.
     */
    public long getCaseId() {
      return caseId_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 4;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 4;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 5;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 5;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 5;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMMIGRATIONSTATUS_FIELD_NUMBER = 6;
    private int immigrationStatus_;
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
     * @return The enum numeric value on the wire for immigrationStatus.
     */
    public int getImmigrationStatusValue() {
      return immigrationStatus_;
    }
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
     * @return The immigrationStatus.
     */
    public io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus getImmigrationStatus() {
      @SuppressWarnings("deprecation")
      io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus result = io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus.valueOf(immigrationStatus_);
      return result == null ? io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus.UNRECOGNIZED : result;
    }

    public static final int ANUMBER_FIELD_NUMBER = 7;
    private int aNumber_;
    /**
     * <code>sint32 aNumber = 7;</code>
     * @return The aNumber.
     */
    public int getANumber() {
      return aNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (caseId_ != 0L) {
        output.writeInt64(1, caseId_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, email_);
      }
      if (immigrationStatus_ != io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus.E3.getNumber()) {
        output.writeEnum(6, immigrationStatus_);
      }
      if (aNumber_ != 0) {
        output.writeSInt32(7, aNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (caseId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, caseId_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, email_);
      }
      if (immigrationStatus_ != io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus.E3.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, immigrationStatus_);
      }
      if (aNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, aNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.demo.pojo.protobuf.CaseV2Impl.Case)) {
        return super.equals(obj);
      }
      io.confluent.demo.pojo.protobuf.CaseV2Impl.Case other = (io.confluent.demo.pojo.protobuf.CaseV2Impl.Case) obj;

      if (getCaseId()
          != other.getCaseId()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (immigrationStatus_ != other.immigrationStatus_) return false;
      if (getANumber()
          != other.getANumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CASEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCaseId());
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + IMMIGRATIONSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + immigrationStatus_;
      hash = (37 * hash) + ANUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getANumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.demo.pojo.protobuf.CaseV2Impl.Case prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.confluent.demo.pojo.protobuf.Case}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.confluent.demo.pojo.protobuf.Case)
        io.confluent.demo.pojo.protobuf.CaseV2Impl.CaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.demo.pojo.protobuf.CaseV2Impl.internal_static_io_confluent_demo_pojo_protobuf_Case_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.demo.pojo.protobuf.CaseV2Impl.internal_static_io_confluent_demo_pojo_protobuf_Case_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.class, io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.Builder.class);
      }

      // Construct using io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        caseId_ = 0L;

        firstName_ = "";

        lastName_ = "";

        address_ = "";

        email_ = "";

        immigrationStatus_ = 0;

        aNumber_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.demo.pojo.protobuf.CaseV2Impl.internal_static_io_confluent_demo_pojo_protobuf_Case_descriptor;
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.CaseV2Impl.Case getDefaultInstanceForType() {
        return io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.CaseV2Impl.Case build() {
        io.confluent.demo.pojo.protobuf.CaseV2Impl.Case result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.CaseV2Impl.Case buildPartial() {
        io.confluent.demo.pojo.protobuf.CaseV2Impl.Case result = new io.confluent.demo.pojo.protobuf.CaseV2Impl.Case(this);
        result.caseId_ = caseId_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.address_ = address_;
        result.email_ = email_;
        result.immigrationStatus_ = immigrationStatus_;
        result.aNumber_ = aNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.demo.pojo.protobuf.CaseV2Impl.Case) {
          return mergeFrom((io.confluent.demo.pojo.protobuf.CaseV2Impl.Case)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.demo.pojo.protobuf.CaseV2Impl.Case other) {
        if (other == io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.getDefaultInstance()) return this;
        if (other.getCaseId() != 0L) {
          setCaseId(other.getCaseId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.immigrationStatus_ != 0) {
          setImmigrationStatusValue(other.getImmigrationStatusValue());
        }
        if (other.getANumber() != 0) {
          setANumber(other.getANumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.confluent.demo.pojo.protobuf.CaseV2Impl.Case parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.confluent.demo.pojo.protobuf.CaseV2Impl.Case) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long caseId_ ;
      /**
       * <code>int64 caseId = 1;</code>
       * @return The caseId.
       */
      public long getCaseId() {
        return caseId_;
      }
      /**
       * <code>int64 caseId = 1;</code>
       * @param value The caseId to set.
       * @return This builder for chaining.
       */
      public Builder setCaseId(long value) {
        
        caseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 caseId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCaseId() {
        
        caseId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 4;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 4;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 4;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 4;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 5;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 5;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 5;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private int immigrationStatus_ = 0;
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
       * @return The enum numeric value on the wire for immigrationStatus.
       */
      public int getImmigrationStatusValue() {
        return immigrationStatus_;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
       * @param value The enum numeric value on the wire for immigrationStatus to set.
       * @return This builder for chaining.
       */
      public Builder setImmigrationStatusValue(int value) {
        immigrationStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
       * @return The immigrationStatus.
       */
      public io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus getImmigrationStatus() {
        @SuppressWarnings("deprecation")
        io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus result = io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus.valueOf(immigrationStatus_);
        return result == null ? io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
       * @param value The immigrationStatus to set.
       * @return This builder for chaining.
       */
      public Builder setImmigrationStatus(io.confluent.demo.pojo.protobuf.CaseV2Impl.Case.ImmigrationStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        immigrationStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Case.ImmigrationStatus immigrationStatus = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearImmigrationStatus() {
        
        immigrationStatus_ = 0;
        onChanged();
        return this;
      }

      private int aNumber_ ;
      /**
       * <code>sint32 aNumber = 7;</code>
       * @return The aNumber.
       */
      public int getANumber() {
        return aNumber_;
      }
      /**
       * <code>sint32 aNumber = 7;</code>
       * @param value The aNumber to set.
       * @return This builder for chaining.
       */
      public Builder setANumber(int value) {
        
        aNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 aNumber = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearANumber() {
        
        aNumber_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.confluent.demo.pojo.protobuf.Case)
    }

    // @@protoc_insertion_point(class_scope:io.confluent.demo.pojo.protobuf.Case)
    private static final io.confluent.demo.pojo.protobuf.CaseV2Impl.Case DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.demo.pojo.protobuf.CaseV2Impl.Case();
    }

    public static io.confluent.demo.pojo.protobuf.CaseV2Impl.Case getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Case>
        PARSER = new com.google.protobuf.AbstractParser<Case>() {
      @java.lang.Override
      public Case parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Case(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Case> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Case> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.demo.pojo.protobuf.CaseV2Impl.Case getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_demo_pojo_protobuf_Case_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_demo_pojo_protobuf_Case_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014caseV2.proto\022\037io.confluent.demo.pojo.p" +
      "rotobuf\"\366\001\n\004Case\022\016\n\006caseId\030\001 \001(\003\022\021\n\tfirs" +
      "tName\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\017\n\007address" +
      "\030\004 \001(\t\022\r\n\005email\030\005 \001(\t\022R\n\021immigrationStat" +
      "us\030\006 \001(\01627.io.confluent.demo.pojo.protob" +
      "uf.Case.ImmigrationStatus\022\017\n\007aNumber\030\007 \001" +
      "(\021\"4\n\021ImmigrationStatus\022\006\n\002E3\020\000\022\007\n\003H1B\020\001" +
      "\022\006\n\002B1\020\002\022\006\n\002B2\020\003B\014B\nCaseV2Implb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_confluent_demo_pojo_protobuf_Case_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_demo_pojo_protobuf_Case_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_demo_pojo_protobuf_Case_descriptor,
        new java.lang.String[] { "CaseId", "FirstName", "LastName", "Address", "Email", "ImmigrationStatus", "ANumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
