// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package io.confluent.demo.pojo.protobuf;

public final class CustomerImpl {
  private CustomerImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.confluent.demo.pojo.protobuf.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 customer_id = 1;</code>
     * @return The customerId.
     */
    long getCustomerId();

    /**
     * <code>string customer_name = 2;</code>
     * @return The customerName.
     */
    java.lang.String getCustomerName();
    /**
     * <code>string customer_name = 2;</code>
     * @return The bytes for customerName.
     */
    com.google.protobuf.ByteString
        getCustomerNameBytes();

    /**
     * <code>string customer_email = 3;</code>
     * @return The customerEmail.
     */
    java.lang.String getCustomerEmail();
    /**
     * <code>string customer_email = 3;</code>
     * @return The bytes for customerEmail.
     */
    com.google.protobuf.ByteString
        getCustomerEmailBytes();

    /**
     * <code>string customer_address = 4;</code>
     * @return The customerAddress.
     */
    java.lang.String getCustomerAddress();
    /**
     * <code>string customer_address = 4;</code>
     * @return The bytes for customerAddress.
     */
    com.google.protobuf.ByteString
        getCustomerAddressBytes();
  }
  /**
   * Protobuf type {@code io.confluent.demo.pojo.protobuf.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.confluent.demo.pojo.protobuf.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      customerName_ = "";
      customerEmail_ = "";
      customerAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              customerId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              customerName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              customerEmail_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              customerAddress_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.demo.pojo.protobuf.CustomerImpl.internal_static_io_confluent_demo_pojo_protobuf_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.demo.pojo.protobuf.CustomerImpl.internal_static_io_confluent_demo_pojo_protobuf_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.class, io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder.class);
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 1;
    private long customerId_;
    /**
     * <code>int64 customer_id = 1;</code>
     * @return The customerId.
     */
    public long getCustomerId() {
      return customerId_;
    }

    public static final int CUSTOMER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object customerName_;
    /**
     * <code>string customer_name = 2;</code>
     * @return The customerName.
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      }
    }
    /**
     * <code>string customer_name = 2;</code>
     * @return The bytes for customerName.
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object customerEmail_;
    /**
     * <code>string customer_email = 3;</code>
     * @return The customerEmail.
     */
    public java.lang.String getCustomerEmail() {
      java.lang.Object ref = customerEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerEmail_ = s;
        return s;
      }
    }
    /**
     * <code>string customer_email = 3;</code>
     * @return The bytes for customerEmail.
     */
    public com.google.protobuf.ByteString
        getCustomerEmailBytes() {
      java.lang.Object ref = customerEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object customerAddress_;
    /**
     * <code>string customer_address = 4;</code>
     * @return The customerAddress.
     */
    public java.lang.String getCustomerAddress() {
      java.lang.Object ref = customerAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string customer_address = 4;</code>
     * @return The bytes for customerAddress.
     */
    public com.google.protobuf.ByteString
        getCustomerAddressBytes() {
      java.lang.Object ref = customerAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (customerId_ != 0L) {
        output.writeInt64(1, customerId_);
      }
      if (!getCustomerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, customerName_);
      }
      if (!getCustomerEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customerEmail_);
      }
      if (!getCustomerAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, customerAddress_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (customerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, customerId_);
      }
      if (!getCustomerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, customerName_);
      }
      if (!getCustomerEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, customerEmail_);
      }
      if (!getCustomerAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, customerAddress_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.demo.pojo.protobuf.CustomerImpl.Customer)) {
        return super.equals(obj);
      }
      io.confluent.demo.pojo.protobuf.CustomerImpl.Customer other = (io.confluent.demo.pojo.protobuf.CustomerImpl.Customer) obj;

      if (getCustomerId()
          != other.getCustomerId()) return false;
      if (!getCustomerName()
          .equals(other.getCustomerName())) return false;
      if (!getCustomerEmail()
          .equals(other.getCustomerEmail())) return false;
      if (!getCustomerAddress()
          .equals(other.getCustomerAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCustomerId());
      hash = (37 * hash) + CUSTOMER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerName().hashCode();
      hash = (37 * hash) + CUSTOMER_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerEmail().hashCode();
      hash = (37 * hash) + CUSTOMER_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.demo.pojo.protobuf.CustomerImpl.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.confluent.demo.pojo.protobuf.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.confluent.demo.pojo.protobuf.Customer)
        io.confluent.demo.pojo.protobuf.CustomerImpl.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.demo.pojo.protobuf.CustomerImpl.internal_static_io_confluent_demo_pojo_protobuf_Customer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.demo.pojo.protobuf.CustomerImpl.internal_static_io_confluent_demo_pojo_protobuf_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.class, io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder.class);
      }

      // Construct using io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        customerId_ = 0L;

        customerName_ = "";

        customerEmail_ = "";

        customerAddress_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.demo.pojo.protobuf.CustomerImpl.internal_static_io_confluent_demo_pojo_protobuf_Customer_descriptor;
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.CustomerImpl.Customer getDefaultInstanceForType() {
        return io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.CustomerImpl.Customer build() {
        io.confluent.demo.pojo.protobuf.CustomerImpl.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.CustomerImpl.Customer buildPartial() {
        io.confluent.demo.pojo.protobuf.CustomerImpl.Customer result = new io.confluent.demo.pojo.protobuf.CustomerImpl.Customer(this);
        result.customerId_ = customerId_;
        result.customerName_ = customerName_;
        result.customerEmail_ = customerEmail_;
        result.customerAddress_ = customerAddress_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.demo.pojo.protobuf.CustomerImpl.Customer) {
          return mergeFrom((io.confluent.demo.pojo.protobuf.CustomerImpl.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.demo.pojo.protobuf.CustomerImpl.Customer other) {
        if (other == io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.getDefaultInstance()) return this;
        if (other.getCustomerId() != 0L) {
          setCustomerId(other.getCustomerId());
        }
        if (!other.getCustomerName().isEmpty()) {
          customerName_ = other.customerName_;
          onChanged();
        }
        if (!other.getCustomerEmail().isEmpty()) {
          customerEmail_ = other.customerEmail_;
          onChanged();
        }
        if (!other.getCustomerAddress().isEmpty()) {
          customerAddress_ = other.customerAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.confluent.demo.pojo.protobuf.CustomerImpl.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.confluent.demo.pojo.protobuf.CustomerImpl.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long customerId_ ;
      /**
       * <code>int64 customer_id = 1;</code>
       * @return The customerId.
       */
      public long getCustomerId() {
        return customerId_;
      }
      /**
       * <code>int64 customer_id = 1;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(long value) {
        
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 customer_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        
        customerId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object customerName_ = "";
      /**
       * <code>string customer_name = 2;</code>
       * @return The customerName.
       */
      public java.lang.String getCustomerName() {
        java.lang.Object ref = customerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customer_name = 2;</code>
       * @return The bytes for customerName.
       */
      public com.google.protobuf.ByteString
          getCustomerNameBytes() {
        java.lang.Object ref = customerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customer_name = 2;</code>
       * @param value The customerName to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string customer_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerName() {
        
        customerName_ = getDefaultInstance().getCustomerName();
        onChanged();
        return this;
      }
      /**
       * <code>string customer_name = 2;</code>
       * @param value The bytes for customerName to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerEmail_ = "";
      /**
       * <code>string customer_email = 3;</code>
       * @return The customerEmail.
       */
      public java.lang.String getCustomerEmail() {
        java.lang.Object ref = customerEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customer_email = 3;</code>
       * @return The bytes for customerEmail.
       */
      public com.google.protobuf.ByteString
          getCustomerEmailBytes() {
        java.lang.Object ref = customerEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customer_email = 3;</code>
       * @param value The customerEmail to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string customer_email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerEmail() {
        
        customerEmail_ = getDefaultInstance().getCustomerEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string customer_email = 3;</code>
       * @param value The bytes for customerEmail to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerEmail_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerAddress_ = "";
      /**
       * <code>string customer_address = 4;</code>
       * @return The customerAddress.
       */
      public java.lang.String getCustomerAddress() {
        java.lang.Object ref = customerAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customer_address = 4;</code>
       * @return The bytes for customerAddress.
       */
      public com.google.protobuf.ByteString
          getCustomerAddressBytes() {
        java.lang.Object ref = customerAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customer_address = 4;</code>
       * @param value The customerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string customer_address = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerAddress() {
        
        customerAddress_ = getDefaultInstance().getCustomerAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string customer_address = 4;</code>
       * @param value The bytes for customerAddress to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerAddress_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.confluent.demo.pojo.protobuf.Customer)
    }

    // @@protoc_insertion_point(class_scope:io.confluent.demo.pojo.protobuf.Customer)
    private static final io.confluent.demo.pojo.protobuf.CustomerImpl.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.demo.pojo.protobuf.CustomerImpl.Customer();
    }

    public static io.confluent.demo.pojo.protobuf.CustomerImpl.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.demo.pojo.protobuf.CustomerImpl.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_demo_pojo_protobuf_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_demo_pojo_protobuf_Customer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\037io.confluent.demo.pojo" +
      ".protobuf\"h\n\010Customer\022\023\n\013customer_id\030\001 \001" +
      "(\003\022\025\n\rcustomer_name\030\002 \001(\t\022\026\n\016customer_em" +
      "ail\030\003 \001(\t\022\030\n\020customer_address\030\004 \001(\tB\016B\014C" +
      "ustomerImplb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_confluent_demo_pojo_protobuf_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_demo_pojo_protobuf_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_demo_pojo_protobuf_Customer_descriptor,
        new java.lang.String[] { "CustomerId", "CustomerName", "CustomerEmail", "CustomerAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
