// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package io.confluent.demo.pojo.protobuf;

public final class OrderImpl {
  private OrderImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.confluent.demo.pojo.protobuf.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 order_id = 1;</code>
     * @return The orderId.
     */
    int getOrderId();

    /**
     * <code>string order_date = 2;</code>
     * @return The orderDate.
     */
    java.lang.String getOrderDate();
    /**
     * <code>string order_date = 2;</code>
     * @return The bytes for orderDate.
     */
    com.google.protobuf.ByteString
        getOrderDateBytes();

    /**
     * <code>int32 order_amount = 3;</code>
     * @return The orderAmount.
     */
    int getOrderAmount();

    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    java.util.List<io.confluent.demo.pojo.protobuf.ProductImpl.Product> 
        getProductsList();
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    io.confluent.demo.pojo.protobuf.ProductImpl.Product getProducts(int index);
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    java.util.List<? extends io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder> 
        getProductsOrBuilderList();
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder getProductsOrBuilder(
        int index);

    /**
     * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
     * @return Whether the customer field is set.
     */
    boolean hasCustomer();
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
     * @return The customer.
     */
    io.confluent.demo.pojo.protobuf.CustomerImpl.Customer getCustomer();
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
     */
    io.confluent.demo.pojo.protobuf.CustomerImpl.CustomerOrBuilder getCustomerOrBuilder();

    /**
     * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
     * @return Whether the paymentMethod field is set.
     */
    boolean hasPaymentMethod();
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
     * @return The paymentMethod.
     */
    io.confluent.demo.pojo.protobuf.PaymentImpl.Payment getPaymentMethod();
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
     */
    io.confluent.demo.pojo.protobuf.PaymentImpl.PaymentOrBuilder getPaymentMethodOrBuilder();
  }
  /**
   * Protobuf type {@code io.confluent.demo.pojo.protobuf.Order}
   */
  public  static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.confluent.demo.pojo.protobuf.Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      orderDate_ = "";
      products_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Order();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              orderId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              orderDate_ = s;
              break;
            }
            case 24: {

              orderAmount_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                products_ = new java.util.ArrayList<io.confluent.demo.pojo.protobuf.ProductImpl.Product>();
                mutable_bitField0_ |= 0x00000001;
              }
              products_.add(
                  input.readMessage(io.confluent.demo.pojo.protobuf.ProductImpl.Product.parser(), extensionRegistry));
              break;
            }
            case 42: {
              io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder subBuilder = null;
              if (customer_ != null) {
                subBuilder = customer_.toBuilder();
              }
              customer_ = input.readMessage(io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(customer_);
                customer_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.Builder subBuilder = null;
              if (paymentMethod_ != null) {
                subBuilder = paymentMethod_.toBuilder();
              }
              paymentMethod_ = input.readMessage(io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(paymentMethod_);
                paymentMethod_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          products_ = java.util.Collections.unmodifiableList(products_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.demo.pojo.protobuf.OrderImpl.internal_static_io_confluent_demo_pojo_protobuf_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.demo.pojo.protobuf.OrderImpl.internal_static_io_confluent_demo_pojo_protobuf_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.demo.pojo.protobuf.OrderImpl.Order.class, io.confluent.demo.pojo.protobuf.OrderImpl.Order.Builder.class);
    }

    public static final int ORDER_ID_FIELD_NUMBER = 1;
    private int orderId_;
    /**
     * <code>int32 order_id = 1;</code>
     * @return The orderId.
     */
    public int getOrderId() {
      return orderId_;
    }

    public static final int ORDER_DATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object orderDate_;
    /**
     * <code>string order_date = 2;</code>
     * @return The orderDate.
     */
    public java.lang.String getOrderDate() {
      java.lang.Object ref = orderDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderDate_ = s;
        return s;
      }
    }
    /**
     * <code>string order_date = 2;</code>
     * @return The bytes for orderDate.
     */
    public com.google.protobuf.ByteString
        getOrderDateBytes() {
      java.lang.Object ref = orderDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_AMOUNT_FIELD_NUMBER = 3;
    private int orderAmount_;
    /**
     * <code>int32 order_amount = 3;</code>
     * @return The orderAmount.
     */
    public int getOrderAmount() {
      return orderAmount_;
    }

    public static final int PRODUCTS_FIELD_NUMBER = 4;
    private java.util.List<io.confluent.demo.pojo.protobuf.ProductImpl.Product> products_;
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    public java.util.List<io.confluent.demo.pojo.protobuf.ProductImpl.Product> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    public java.util.List<? extends io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder> 
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    public io.confluent.demo.pojo.protobuf.ProductImpl.Product getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
     */
    public io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    public static final int CUSTOMER_FIELD_NUMBER = 5;
    private io.confluent.demo.pojo.protobuf.CustomerImpl.Customer customer_;
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
     * @return Whether the customer field is set.
     */
    public boolean hasCustomer() {
      return customer_ != null;
    }
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
     * @return The customer.
     */
    public io.confluent.demo.pojo.protobuf.CustomerImpl.Customer getCustomer() {
      return customer_ == null ? io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.getDefaultInstance() : customer_;
    }
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
     */
    public io.confluent.demo.pojo.protobuf.CustomerImpl.CustomerOrBuilder getCustomerOrBuilder() {
      return getCustomer();
    }

    public static final int PAYMENT_METHOD_FIELD_NUMBER = 6;
    private io.confluent.demo.pojo.protobuf.PaymentImpl.Payment paymentMethod_;
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
     * @return Whether the paymentMethod field is set.
     */
    public boolean hasPaymentMethod() {
      return paymentMethod_ != null;
    }
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
     * @return The paymentMethod.
     */
    public io.confluent.demo.pojo.protobuf.PaymentImpl.Payment getPaymentMethod() {
      return paymentMethod_ == null ? io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.getDefaultInstance() : paymentMethod_;
    }
    /**
     * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
     */
    public io.confluent.demo.pojo.protobuf.PaymentImpl.PaymentOrBuilder getPaymentMethodOrBuilder() {
      return getPaymentMethod();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0) {
        output.writeInt32(1, orderId_);
      }
      if (!getOrderDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderDate_);
      }
      if (orderAmount_ != 0) {
        output.writeInt32(3, orderAmount_);
      }
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(4, products_.get(i));
      }
      if (customer_ != null) {
        output.writeMessage(5, getCustomer());
      }
      if (paymentMethod_ != null) {
        output.writeMessage(6, getPaymentMethod());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, orderId_);
      }
      if (!getOrderDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderDate_);
      }
      if (orderAmount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, orderAmount_);
      }
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, products_.get(i));
      }
      if (customer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCustomer());
      }
      if (paymentMethod_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getPaymentMethod());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.demo.pojo.protobuf.OrderImpl.Order)) {
        return super.equals(obj);
      }
      io.confluent.demo.pojo.protobuf.OrderImpl.Order other = (io.confluent.demo.pojo.protobuf.OrderImpl.Order) obj;

      if (getOrderId()
          != other.getOrderId()) return false;
      if (!getOrderDate()
          .equals(other.getOrderDate())) return false;
      if (getOrderAmount()
          != other.getOrderAmount()) return false;
      if (!getProductsList()
          .equals(other.getProductsList())) return false;
      if (hasCustomer() != other.hasCustomer()) return false;
      if (hasCustomer()) {
        if (!getCustomer()
            .equals(other.getCustomer())) return false;
      }
      if (hasPaymentMethod() != other.hasPaymentMethod()) return false;
      if (hasPaymentMethod()) {
        if (!getPaymentMethod()
            .equals(other.getPaymentMethod())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId();
      hash = (37 * hash) + ORDER_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderDate().hashCode();
      hash = (37 * hash) + ORDER_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getOrderAmount();
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      if (hasCustomer()) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomer().hashCode();
      }
      if (hasPaymentMethod()) {
        hash = (37 * hash) + PAYMENT_METHOD_FIELD_NUMBER;
        hash = (53 * hash) + getPaymentMethod().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.demo.pojo.protobuf.OrderImpl.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.confluent.demo.pojo.protobuf.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.confluent.demo.pojo.protobuf.Order)
        io.confluent.demo.pojo.protobuf.OrderImpl.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.demo.pojo.protobuf.OrderImpl.internal_static_io_confluent_demo_pojo_protobuf_Order_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.demo.pojo.protobuf.OrderImpl.internal_static_io_confluent_demo_pojo_protobuf_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.demo.pojo.protobuf.OrderImpl.Order.class, io.confluent.demo.pojo.protobuf.OrderImpl.Order.Builder.class);
      }

      // Construct using io.confluent.demo.pojo.protobuf.OrderImpl.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        orderId_ = 0;

        orderDate_ = "";

        orderAmount_ = 0;

        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productsBuilder_.clear();
        }
        if (customerBuilder_ == null) {
          customer_ = null;
        } else {
          customer_ = null;
          customerBuilder_ = null;
        }
        if (paymentMethodBuilder_ == null) {
          paymentMethod_ = null;
        } else {
          paymentMethod_ = null;
          paymentMethodBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.demo.pojo.protobuf.OrderImpl.internal_static_io_confluent_demo_pojo_protobuf_Order_descriptor;
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.OrderImpl.Order getDefaultInstanceForType() {
        return io.confluent.demo.pojo.protobuf.OrderImpl.Order.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.OrderImpl.Order build() {
        io.confluent.demo.pojo.protobuf.OrderImpl.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.demo.pojo.protobuf.OrderImpl.Order buildPartial() {
        io.confluent.demo.pojo.protobuf.OrderImpl.Order result = new io.confluent.demo.pojo.protobuf.OrderImpl.Order(this);
        int from_bitField0_ = bitField0_;
        result.orderId_ = orderId_;
        result.orderDate_ = orderDate_;
        result.orderAmount_ = orderAmount_;
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
        if (customerBuilder_ == null) {
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
        if (paymentMethodBuilder_ == null) {
          result.paymentMethod_ = paymentMethod_;
        } else {
          result.paymentMethod_ = paymentMethodBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.demo.pojo.protobuf.OrderImpl.Order) {
          return mergeFrom((io.confluent.demo.pojo.protobuf.OrderImpl.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.demo.pojo.protobuf.OrderImpl.Order other) {
        if (other == io.confluent.demo.pojo.protobuf.OrderImpl.Order.getDefaultInstance()) return this;
        if (other.getOrderId() != 0) {
          setOrderId(other.getOrderId());
        }
        if (!other.getOrderDate().isEmpty()) {
          orderDate_ = other.orderDate_;
          onChanged();
        }
        if (other.getOrderAmount() != 0) {
          setOrderAmount(other.getOrderAmount());
        }
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        if (other.hasCustomer()) {
          mergeCustomer(other.getCustomer());
        }
        if (other.hasPaymentMethod()) {
          mergePaymentMethod(other.getPaymentMethod());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.confluent.demo.pojo.protobuf.OrderImpl.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.confluent.demo.pojo.protobuf.OrderImpl.Order) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int orderId_ ;
      /**
       * <code>int32 order_id = 1;</code>
       * @return The orderId.
       */
      public int getOrderId() {
        return orderId_;
      }
      /**
       * <code>int32 order_id = 1;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(int value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 order_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        
        orderId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object orderDate_ = "";
      /**
       * <code>string order_date = 2;</code>
       * @return The orderDate.
       */
      public java.lang.String getOrderDate() {
        java.lang.Object ref = orderDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string order_date = 2;</code>
       * @return The bytes for orderDate.
       */
      public com.google.protobuf.ByteString
          getOrderDateBytes() {
        java.lang.Object ref = orderDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string order_date = 2;</code>
       * @param value The orderDate to set.
       * @return This builder for chaining.
       */
      public Builder setOrderDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string order_date = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderDate() {
        
        orderDate_ = getDefaultInstance().getOrderDate();
        onChanged();
        return this;
      }
      /**
       * <code>string order_date = 2;</code>
       * @param value The bytes for orderDate to set.
       * @return This builder for chaining.
       */
      public Builder setOrderDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderDate_ = value;
        onChanged();
        return this;
      }

      private int orderAmount_ ;
      /**
       * <code>int32 order_amount = 3;</code>
       * @return The orderAmount.
       */
      public int getOrderAmount() {
        return orderAmount_;
      }
      /**
       * <code>int32 order_amount = 3;</code>
       * @param value The orderAmount to set.
       * @return This builder for chaining.
       */
      public Builder setOrderAmount(int value) {
        
        orderAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 order_amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderAmount() {
        
        orderAmount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<io.confluent.demo.pojo.protobuf.ProductImpl.Product> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          products_ = new java.util.ArrayList<io.confluent.demo.pojo.protobuf.ProductImpl.Product>(products_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.confluent.demo.pojo.protobuf.ProductImpl.Product, io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder, io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder> productsBuilder_;

      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public java.util.List<io.confluent.demo.pojo.protobuf.ProductImpl.Product> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public io.confluent.demo.pojo.protobuf.ProductImpl.Product getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder setProducts(
          int index, io.confluent.demo.pojo.protobuf.ProductImpl.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder setProducts(
          int index, io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder addProducts(io.confluent.demo.pojo.protobuf.ProductImpl.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder addProducts(
          int index, io.confluent.demo.pojo.protobuf.ProductImpl.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder addProducts(
          io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder addProducts(
          int index, io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder addAllProducts(
          java.lang.Iterable<? extends io.confluent.demo.pojo.protobuf.ProductImpl.Product> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public java.util.List<? extends io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder> 
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
            io.confluent.demo.pojo.protobuf.ProductImpl.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index, io.confluent.demo.pojo.protobuf.ProductImpl.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .io.confluent.demo.pojo.protobuf.Product products = 4;</code>
       */
      public java.util.List<io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder> 
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.confluent.demo.pojo.protobuf.ProductImpl.Product, io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder, io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder> 
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.confluent.demo.pojo.protobuf.ProductImpl.Product, io.confluent.demo.pojo.protobuf.ProductImpl.Product.Builder, io.confluent.demo.pojo.protobuf.ProductImpl.ProductOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }

      private io.confluent.demo.pojo.protobuf.CustomerImpl.Customer customer_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.confluent.demo.pojo.protobuf.CustomerImpl.Customer, io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder, io.confluent.demo.pojo.protobuf.CustomerImpl.CustomerOrBuilder> customerBuilder_;
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       * @return Whether the customer field is set.
       */
      public boolean hasCustomer() {
        return customerBuilder_ != null || customer_ != null;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       * @return The customer.
       */
      public io.confluent.demo.pojo.protobuf.CustomerImpl.Customer getCustomer() {
        if (customerBuilder_ == null) {
          return customer_ == null ? io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.getDefaultInstance() : customer_;
        } else {
          return customerBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       */
      public Builder setCustomer(io.confluent.demo.pojo.protobuf.CustomerImpl.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          customer_ = value;
          onChanged();
        } else {
          customerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       */
      public Builder setCustomer(
          io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          customer_ = builderForValue.build();
          onChanged();
        } else {
          customerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       */
      public Builder mergeCustomer(io.confluent.demo.pojo.protobuf.CustomerImpl.Customer value) {
        if (customerBuilder_ == null) {
          if (customer_ != null) {
            customer_ =
              io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.newBuilder(customer_).mergeFrom(value).buildPartial();
          } else {
            customer_ = value;
          }
          onChanged();
        } else {
          customerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = null;
          onChanged();
        } else {
          customer_ = null;
          customerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       */
      public io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder getCustomerBuilder() {
        
        onChanged();
        return getCustomerFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       */
      public io.confluent.demo.pojo.protobuf.CustomerImpl.CustomerOrBuilder getCustomerOrBuilder() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilder();
        } else {
          return customer_ == null ?
              io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.getDefaultInstance() : customer_;
        }
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Customer customer = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.confluent.demo.pojo.protobuf.CustomerImpl.Customer, io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder, io.confluent.demo.pojo.protobuf.CustomerImpl.CustomerOrBuilder> 
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.confluent.demo.pojo.protobuf.CustomerImpl.Customer, io.confluent.demo.pojo.protobuf.CustomerImpl.Customer.Builder, io.confluent.demo.pojo.protobuf.CustomerImpl.CustomerOrBuilder>(
                  getCustomer(),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }

      private io.confluent.demo.pojo.protobuf.PaymentImpl.Payment paymentMethod_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.confluent.demo.pojo.protobuf.PaymentImpl.Payment, io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.Builder, io.confluent.demo.pojo.protobuf.PaymentImpl.PaymentOrBuilder> paymentMethodBuilder_;
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       * @return Whether the paymentMethod field is set.
       */
      public boolean hasPaymentMethod() {
        return paymentMethodBuilder_ != null || paymentMethod_ != null;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       * @return The paymentMethod.
       */
      public io.confluent.demo.pojo.protobuf.PaymentImpl.Payment getPaymentMethod() {
        if (paymentMethodBuilder_ == null) {
          return paymentMethod_ == null ? io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.getDefaultInstance() : paymentMethod_;
        } else {
          return paymentMethodBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       */
      public Builder setPaymentMethod(io.confluent.demo.pojo.protobuf.PaymentImpl.Payment value) {
        if (paymentMethodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          paymentMethod_ = value;
          onChanged();
        } else {
          paymentMethodBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       */
      public Builder setPaymentMethod(
          io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.Builder builderForValue) {
        if (paymentMethodBuilder_ == null) {
          paymentMethod_ = builderForValue.build();
          onChanged();
        } else {
          paymentMethodBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       */
      public Builder mergePaymentMethod(io.confluent.demo.pojo.protobuf.PaymentImpl.Payment value) {
        if (paymentMethodBuilder_ == null) {
          if (paymentMethod_ != null) {
            paymentMethod_ =
              io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.newBuilder(paymentMethod_).mergeFrom(value).buildPartial();
          } else {
            paymentMethod_ = value;
          }
          onChanged();
        } else {
          paymentMethodBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       */
      public Builder clearPaymentMethod() {
        if (paymentMethodBuilder_ == null) {
          paymentMethod_ = null;
          onChanged();
        } else {
          paymentMethod_ = null;
          paymentMethodBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       */
      public io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.Builder getPaymentMethodBuilder() {
        
        onChanged();
        return getPaymentMethodFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       */
      public io.confluent.demo.pojo.protobuf.PaymentImpl.PaymentOrBuilder getPaymentMethodOrBuilder() {
        if (paymentMethodBuilder_ != null) {
          return paymentMethodBuilder_.getMessageOrBuilder();
        } else {
          return paymentMethod_ == null ?
              io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.getDefaultInstance() : paymentMethod_;
        }
      }
      /**
       * <code>.io.confluent.demo.pojo.protobuf.Payment payment_method = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.confluent.demo.pojo.protobuf.PaymentImpl.Payment, io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.Builder, io.confluent.demo.pojo.protobuf.PaymentImpl.PaymentOrBuilder> 
          getPaymentMethodFieldBuilder() {
        if (paymentMethodBuilder_ == null) {
          paymentMethodBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.confluent.demo.pojo.protobuf.PaymentImpl.Payment, io.confluent.demo.pojo.protobuf.PaymentImpl.Payment.Builder, io.confluent.demo.pojo.protobuf.PaymentImpl.PaymentOrBuilder>(
                  getPaymentMethod(),
                  getParentForChildren(),
                  isClean());
          paymentMethod_ = null;
        }
        return paymentMethodBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.confluent.demo.pojo.protobuf.Order)
    }

    // @@protoc_insertion_point(class_scope:io.confluent.demo.pojo.protobuf.Order)
    private static final io.confluent.demo.pojo.protobuf.OrderImpl.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.demo.pojo.protobuf.OrderImpl.Order();
    }

    public static io.confluent.demo.pojo.protobuf.OrderImpl.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.demo.pojo.protobuf.OrderImpl.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_demo_pojo_protobuf_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_demo_pojo_protobuf_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\037io.confluent.demo.pojo.pr" +
      "otobuf\032\rproduct.proto\032\016customer.proto\032\rp" +
      "ayment.proto\"\376\001\n\005Order\022\020\n\010order_id\030\001 \001(\005" +
      "\022\022\n\norder_date\030\002 \001(\t\022\024\n\014order_amount\030\003 \001" +
      "(\005\022:\n\010products\030\004 \003(\0132(.io.confluent.demo" +
      ".pojo.protobuf.Product\022;\n\010customer\030\005 \001(\013" +
      "2).io.confluent.demo.pojo.protobuf.Custo" +
      "mer\022@\n\016payment_method\030\006 \001(\0132(.io.conflue" +
      "nt.demo.pojo.protobuf.PaymentB\013B\tOrderIm" +
      "plb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.confluent.demo.pojo.protobuf.ProductImpl.getDescriptor(),
          io.confluent.demo.pojo.protobuf.CustomerImpl.getDescriptor(),
          io.confluent.demo.pojo.protobuf.PaymentImpl.getDescriptor(),
        });
    internal_static_io_confluent_demo_pojo_protobuf_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_demo_pojo_protobuf_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_demo_pojo_protobuf_Order_descriptor,
        new java.lang.String[] { "OrderId", "OrderDate", "OrderAmount", "Products", "Customer", "PaymentMethod", });
    io.confluent.demo.pojo.protobuf.ProductImpl.getDescriptor();
    io.confluent.demo.pojo.protobuf.CustomerImpl.getDescriptor();
    io.confluent.demo.pojo.protobuf.PaymentImpl.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
